# Generated by Django 5.0 on 2025-11-28 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clubs', '0002_club_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_club_members', to='clubs.club'),
        ),
    ]
