# Generated by Django 6.0.2 on 2026-03-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_sub_club'),
        ('clubs', '0003_club_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_clubs',
            field=models.ManyToManyField(blank=True, help_text='Additional clubs this user can create/manage events for', related_name='extra_members', to='clubs.club'),
        ),
    ]
