# Generated by Django 5.0 on 2026-03-08 09:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_extra_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_time',
            field=models.TimeField(blank=True, default=accounts.models.get_random_notification_time, help_text="Time to send daily notification (in user's timezone)", null=True),
        ),
    ]
