# Generated by Django 5.0 on 2026-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_randomize_existing_notification_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_format',
            field=models.CharField(choices=[('12h', '12 Hour'), ('24h', '24 Hour')], default='12h', help_text="User's preferred time format", max_length=3),
        ),
    ]
