# Generated by Django 6.0.2 on 2026-03-07 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0003_club_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.CharField(help_text="Event location (e.g., 'CS Lab 2', 'Main Auditorium')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club')),
                ('collaborating_clubs', models.ManyToManyField(blank=True, help_text='Other clubs co-organizing this event', related_name='collaborated_events', to='clubs.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
                'indexes': [models.Index(fields=['start', 'end'], name='events_even_start_bfe45a_idx'), models.Index(fields=['club', 'created_at'], name='events_even_club_id_e096f1_idx')],
            },
        ),
    ]
