# Generated by Django 6.0.2 on 2026-03-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_order'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='collaborating_clubs',
            field=models.ManyToManyField(blank=True, help_text='Other clubs co-organizing this event', related_name='collaborated_events', to='clubs.club'),
        ),
    ]
