# Generated by Django 6.0.2 on 2026-03-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='order',
            field=models.IntegerField(default=0, help_text='Manual display order'),
        ),
    ]
